[package]
name = "phasetida-core"
version = "0.1.14"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
